### ISSUE TITLE
Curl OUTPUT

### ISSUE THREAD

**Issue by johnpaulmedina** [luckymarmot/Paw-PHPcURLCodeGenerator#1]
Prior to this release the way the curl code was outputted was much cleaner and nicer. How can I make adjustments to do that again.

Curl would work better as an output like so:

``` php
$post = array();
$post['first_name'] = 'Someone';
$post['last_name'] = 'Else';
```

or Even 

``` php
$post = array(
   'first_name' => 'Someone',
   'last_name' => 'Else'
);
```

For me the idea behind paw is FAST testing and posting to API's but when I want to implement them in my code I usually need to swap out the hard coded values to be dynamic values like $user['first_name'] but when its all in one line it makes it much more complicated to edit that curl request and or make changes quickly.

I took a look at the coffeeScript file but I am not familiar with coffeeScript can you guys point me in the direction please.

**Comment by kwent** [comment]
I'm not sure to understand what you are saying. Which prior version are you talking about ?

What is different from what you are saying except the `Short array syntax []` available since [PHP 5.4.0](http://php.net/manual/en/migration54.new-features.php)

Below one output example : 

``` php
<?php

// Get cURL resource
$ch = curl_init();

// Set url
curl_setopt($ch, CURLOPT_URL, 'http://httpbin.org/post');

// Set method
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');

// Set options
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// Create body
$body = [
  "multipart-key2" => "multipart-value2",
  "multipart-key1" => "multipart-value1",
  "multipart-date-key" => "Thu, 05 Feb 2015 19:15:10 GMT",
  "multipart-nonce-key" => "rhLGlw3Fbvag82WCGFlHWuJGS0PtJIgN",
  ];

// Set body
curl_setopt($ch, CURLOPT_POST, 1); 
curl_setopt($ch, CURLOPT_POSTFIELDS, $body);

// Send the request & save response to $resp
$resp = curl_exec($ch);

if(!$resp) {
  die('Error: "' . curl_error($ch) . '" - Code: ' . curl_errno($ch));
} else {
  echo "Response HTTP Status Code : " . curl_getinfo($ch, CURLINFO_HTTP_CODE);
  echo "\nResponse HTTP Body : " . $resp;
}

// Close request to clear up some resources
curl_close($ch);

?>
```

**Comment by johnpaulmedina** [comment]
Not sure of the version but this is how my APP creates the body:

``` php
// Create body
$body = 'state=FL&xxTest=true&xxCampaignId=056la95sx&timestamp=2015-02-05 13:32:30&affkey=77920&xxAccountId=056008luc&first_name=Joe&postal_code=33193&last_name=Robbins&ip_address=127.0.0.1&email=joe.robbins.213222@gmail.com&primary_phone=3059876989&';
```

Its literally in one line. What you put above is much cleaner. Any reason why I am seeing 1 jumbled line. It does not make it easy to edit or change once I implement that code.

**Comment by johnpaulmedina** [comment]
There was a major release to paw which included these extensions. It use to be "built" in so to speak. When it was built in it gave code similar to what you provided. Now its like the code I placed above

**Comment by kwent** [comment]
Ok it looks like it's only for `Form URL-Encoded` format. Do you confirm ?

**Comment by johnpaulmedina** [comment]
Ahhh YESSS!!!!!

**Comment by johnpaulmedina** [comment]
Multipart works great

**Comment by johnpaulmedina** [comment]
What can I change if i wanted it to be `$body['value'] = 'value';`

I like the shorthand array but sometimes I would much rather it be broken up individually. When we bring that code into a production environment swapping the values to dynamic values of the page it is being placed on would be much quicker if they were broke up individually.

**Comment by kwent** [comment]
From the [manual](http://php.net/manual/en/function.curl-setopt.php#refsect1-function.curl-setopt-notes)

**Passing an array to CURLOPT_POSTFIELDS will encode the data as multipart/form-data, while passing a URL-encoded string will encode the data as application/x-www-form-urlencoded.**

That's why.

Regards,

**Comment by johnpaulmedina** [comment]
I get that part but then why not put 

`http_build_query($body)`

when the user selects `Form-Url Encoded`

It may be a personal preference but I generally use PAW to test API calls and see quick responses and when we are ready we put it in to production and having the extension to go to PHP curl format makes it so much easier to move it into production except that the values I pass are test values and generally get switched to dynamic values it just makes more sense to be able to visually in the code be able to change the values to dynamic options. Using the extension to output code with hard coded values is just unrealistic unless you make an API call with the same values every time.

Thanks,
JP

**Comment by kwent** [comment]
Ok let me see what i can do.

**Comment by johnpaulmedina** [comment]
Thanks for your prompt replies

**Comment by kwent** [comment]
Ok could you try this new release [v1.0.2](https://github.com/luckymarmot/Paw-PHPcURLCodeGenerator/releases/tag/v1.0.2) and let me know if it's better for you ?

Btw did you know you can play with environment feature to switch between test environment and production environment ?

Regards,

**Comment by johnpaulmedina** [comment]
Yes thats good for the form url encoded. What do you mean by environment feature?

**Comment by kwent** [comment]
https://luckymarmot.com/paw/doc/Environments
