### ISSUE TITLE
Overwriting all headers with Content-Type header

### ISSUE THREAD

**Issue by maricn** [luckymarmot/Paw-PHPcURLCodeGenerator#3]
Your mustache script first sets my headers, and then overwrites them with yours hardcoded "Content-Type: application/json".

**Comment by jeroenvisser101** [comment]
@maricn you're right, but that only happens when `body.has_raw_body` evaluates to true, so I think that's on purpose, but might have to be revised if it's causing you trouble.

**Comment by maricn** [comment]
Sincerely, setting body type to JSON is not in human readable format for me. :D
I understand the need for some convention (defaulting to `application/json`) if body type is not set in editor, but it would be better to first check if `Content-Type` header already exists, and then set it.

**Comment by jeroenvisser101** [comment]
I'm sorry, I misread your Content-Type.

We set the content type to `text/plain` when `body.has_raw_body` is true:

```
{{#body.has_raw_body}}
// Set header
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: text/plain']);

// Create body
$body = '{{{body.raw_body}}}';
{{/body.has_raw_body}}
```

However, we set it to application/json when the content is JSON:

```
{{#body.has_json_body}}
// Set header
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json']);

// Create body
$json_array = {{{body.json_body_object}}}; 
$body = json_encode($json_array);
{{/body.has_json_body}}
```

As it overwrites the headers you've set yourself, I think it would be best to move the custom headers down a bit, which would allow for both setting your own headers, and overwriting the content-type. What do you think?

**Comment by maricn** [comment]
I agree. :+1: 
I'm glad we found a satisfying solution; thanks for such quick answers.

**Comment by jeroenvisser101** [comment]
I've created a pull-request. If you could confirm that that fixes the issue you're experiencing, that'd be great!

**Comment by maricn** [comment]
Hmm. It's fine for me, but if anyone is specifying headers without `Content-Type` header present, curl_setopt will overwrite previously set `Content-Type` header leaving the request without it.

**Comment by jeroenvisser101** [comment]
Hmmm, you're right, maybe this should not be done in the mustache template at all, it would be easier to do these overrides in the importer itself, would make the code cleaner too!

**Comment by JonathanMontane** [comment]
fixed.
