### ISSUE TITLE
Importing JSON doesn't use the JSON Widget Correctly

### ISSUE THREAD

**Issue by derimagia** [luckymarmot/Paw-PHPcURLCodeGenerator#6]
Steps to reproduce:

1) Import a CURL Request that is a POST with the body being JSON
2) Notice the "Body" of the imported request is JSON but doesn't use the JSON widget properly and instead if just a string

**Comment by derimagia** [comment]
Sorry, this is my mistake. The data I imported was invalid. Closing this for now.

**Comment by mittsh** [comment]
@Derimagia sorry for the late follow up, I've tried it myself with a JSON body and it works fine too, but thanks for contributing!

![image](https://cloud.githubusercontent.com/assets/1319906/12180183/600da912-b57b-11e5-80ac-eb74104fe600.png)
